# Generated by Django 3.2.7 on 2021-09-27 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20210927_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodels',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
